# Generated by Django 5.1.3 on 2024-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_profile_email_remove_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="My Bio...", max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/static/images/avatar_default.svg",
                null=True,
                upload_to="uploads/profile_pictures/%Y/%m/%d/",
            ),
        ),
    ]
