# Generated by Django 5.1.3 on 2024-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_bio_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="static/images/profile_picture_default.svg",
                null=True,
                upload_to="uploads/profile_pictures/%Y/%m/%d/",
            ),
        ),
    ]
