# Generated by Django 5.1.3 on 2024-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="defaults/profile_picture_default.png",
                null=True,
                upload_to="uploads/profile_pictures/%Y/%m/%d/",
            ),
        ),
    ]
