# Generated by Django 5.1.3 on 2024-11-16 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.TextField()),
                ("updated_by", models.TextField()),
                ("is_active", models.BooleanField()),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("position", models.PositiveIntegerField()),
                ("card_limit", models.PositiveIntegerField()),
                ("due_date", models.DateTimeField()),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.TextField()),
                ("updated_by", models.TextField()),
                ("is_active", models.BooleanField()),
                ("title", models.CharField(max_length=250)),
                ("position", models.PositiveIntegerField()),
                ("card_limit", models.PositiveIntegerField()),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CardAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.TextField()),
                ("updated_by", models.TextField()),
                ("is_active", models.BooleanField()),
                ("filename", models.CharField(max_length=250)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/attachments/%Y/%m/%d/"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_attachments",
                        to="kanban.card",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CardThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.TextField()),
                ("updated_by", models.TextField()),
                ("is_active", models.BooleanField()),
                ("filename", models.CharField(max_length=250)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="uploads/thumbnails/%Y/%m/%d/",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_thumbnails",
                        to="kanban.card",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="card",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="kanban.column",
            ),
        ),
        migrations.CreateModel(
            name="Kanban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.TextField()),
                ("updated_by", models.TextField()),
                ("is_active", models.BooleanField()),
                ("title", models.CharField(max_length=250)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kanbans",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="column",
            name="kanban",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="columns",
                to="kanban.kanban",
            ),
        ),
    ]
