# Generated by Django 5.1.3 on 2024-11-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="column",
            name="is_public",
        ),
    ]
