# Generated by Django 5.1.3 on 2024-12-06 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanban",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True, editable=False, unique=True),
        ),
    ]
