# Generated by Django 5.1.3 on 2024-11-16 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0002_remove_card_is_public_remove_column_is_public"),
        ("profiles", "0002_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="cardattachment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="cardattachment",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="cardthumbnail",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="cardthumbnail",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="column",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="column",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="kanban",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="kanban",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="profiles.profile",
            ),
        ),
    ]
