# Generated by Django 5.1.3 on 2024-12-06 08:06

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Kanban = apps.get_model("kanban", "Kanban")
    for row in Kanban.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0002_add_uuid_field"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
