# Generated by Django 5.1.3 on 2024-11-16 22:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0003_alter_card_created_by_alter_card_updated_by_and_more"),
        ("profiles", "0002_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="profiles.profile",
                    ),
                ),
                (
                    "kanban",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="kanban.kanban",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_members",
                        to="profiles.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("kanban", "profile")},
            },
        ),
    ]
