# Generated by Django 5.1.3 on 2024-12-06 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0003_populate_uuid_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanban",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
