# Generated by Django 5.1.3 on 2024-12-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0004_rename_uuid_nuill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="card_limit",
        ),
    ]
