# Generated by Django 5.1.3 on 2024-11-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0004_kanbanmember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kanbanmember",
            name="added_on",
        ),
    ]
