# Generated by Django 5.1.3 on 2024-12-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0005_remove_card_card_limit"),
        ("profiles", "0007_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="kanban",
            constraint=models.UniqueConstraint(
                fields=("title", "profile"), name="kanban_title_unique_to_user"
            ),
        ),
    ]
