# Generated by Django 5.1.3 on 2024-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0005_remove_kanbanmember_added_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cardattachment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cardthumbnail",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="column",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="kanban",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
