# Generated by Django 5.1.3 on 2024-12-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0006_kanban_kanban_title_unique_to_user"),
        ("profiles", "0007_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kanbanmember",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="kanbanmember",
            constraint=models.UniqueConstraint(
                fields=("kanban", "profile"), name="kanban_unique_to_user"
            ),
        ),
    ]
