# Generated by Django 5.1.3 on 2024-11-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0006_alter_card_is_active_alter_cardattachment_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardthumbnail",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/thumbnails/%Y/%m/%d/"
            ),
        ),
    ]
